### ISSUE TITLE
How can I get which indicator is currently focusing?

### ISSUE THREAD

**Issue by umangce** [LyndonChin/AndroidRubberIndicator#2]
Hi Lyndon Chin,

Your work is awesome friend. Just I want to know that if there are three indicators if users select 3rd one then how can we know that? And if i want to focus on 3rd indicator directly that thing how can i achieve?

Thanks.

**Comment by LyndonChin** [comment]
@umangce Thank you for your consideration. The function to focus on the specified indicator is not yet added, but I'll add it soon. 

Your contribution is welcome. :)
